var comment = {
		error : "오류가 발생됬습니다.\n관리자에게 문의하세요.",
		error_image_file_include_korean :"이미지 파일에 한글이 포함되어있습니다.",
		auth_error : "권한이 없습니다.",
		cancel : "취소되었습니다.",
		insert_number : "숫자를 입력하세요.",
		insert_id : "아이디를 입력하세요.",
		insert_password : "비밀번호를 입력하세요",
		download : "다운로드",
		insert : "등록",
		update : "수정",
		
		isInsert : "등록하시겠습니까?",
		isUpdate : "수정하시겠습니까?",
		isUpdate2 : "변경된 내용을 저장 하시겠습니까?",
		isDelete : "삭제하시겠습니까?",
		isAdd : "추가하시겠습니까?",
		isExcelDownload : "엑셀표를 다운로드 받으시겠습니까?",
		isSend : "발송하시겠습니까?",
		isCancel : "취소하시겠습니까?",
		isSave : "저장 하시겠습니까?",
    	isSave2 : "입력된 정보를 저장 하시겠습니까?",
		isChange : "변경하시겠습니까?",

		select_member : "멤버 종류를 선택하세요.",
		select_search_list : "검색종류를 선택하세요.",
		select_year : "년도를 선택하세요.",
		select_product : "상품종류를 선택하세요.",
		select_item : "아이템종류를 선택하세요.",
		select_start_date : "시작일을 선택하세요.",
		select_end_date : "종료일을 선택하세요.",
		select_search_date : "검색일을 선택하세요.",
		select_excel_file : "엑셀파일을 선택하세요.",
		select_category : "구분을 선택하세요.",
		select_status : "상태를 선택하세요.",


		check_item : "항목을 체크하세요.",
		not_update_item : "변경될 항목이 없습니다.",
		
		blank_list : "목록이 없습니다.",
    	blank_lecture_list : "수강 이력이 없습니다.",
		blank_list2 : "검색 결과가 없습니다.",
		blank_result : "결과가 없습니다.",
		blank_search_result : "검색된 결과가 없습니다.",
		blank_check_all : "체크된 항목이 없습니다. 전체체크 하세요.",
		blank_check : "체크된 값이 없습니다.",
		blank_login_check : "아이디 또는 비밀번호를 확인해 주세요.",
		black_login_password_check : "가입 정보가 일치하지 않습니다. 아이디 또는 이메일 주소를 확인해 주세요. ",
		success_withdrawral : "회원탈퇴가 정상적으로 처리되었습니다.",
		success_process : "완료됬습니다.",
		success_delete : "삭제되었습니다.",
		success_cancel : "취소되었습니다.",
		success_update : "수정됬습니다.",

		load_data : "데이타를 불러오는중..",

    	input_academy_group : "그룹명을 선택하세요.",
		input_academy_name : "학원명을 입력해주세요.",
        input_academy_directorname : "학원원장명을 입력해주세요.",
		input_academy_phone1 : "핸드폰번호 입력해주세요.",
		input_academy_phone2 : "핸드폰번호 입력해주세요.",
		input_academy_phone3 : "핸드폰번호 입력해주세요.",
        input_academy_address : "학원주소를 입력해주세요",
    	input_academy_address_detail : "학원상세주소를 입력해주세요",
		input_academy_fax : "팩스번호를 입력해주세요.",
    	input_register_date : "등록일을 입력해주세요.",
    	input_busdriver_number : "차량번호를 입력해주세요.",
    	input_busPass_number : "승차정원을 입력해주세요.",
    	input_bussafe_date : "안전필증을 입력해주세요.",

		input_zip_code : "우편번호를 입력하세요.",


    	input_member_type : "유형을 선택해주세요.",
    	input_member_posiotion:"직책을 선택해주세요.",
    	input_member_academy:"소속을 선택해주세요.",
    	input_member_team:"소속팀을 선택해주세요.",
		input_member_name : "직원명을 입력해주세요.",
    	input_mother_name : "부모님(모)명을 입력해주세요.",
		input_member_phone1 : "핸드폰번호 입력해주세요.",
    	input_member_phone2 : "핸드폰번호 입력해주세요.",
    	input_member_phone3 : "핸드폰번호 입력해주세요.",
		input_member_startDate : "생년월일을 입력해주세요.",
		input_member_tel1 : "전화번호를 입력해주세요.",
		input_member_tel2 : "전화번호를 입력해주세요",
		input_member_tel3 : "전화번호를 입력해주세요",
		input_mother_tel1 : "부모님(모) 전화번호를 입력해주세요.",
		input_mother_tel2 : "부모님(모)전화번호를 입력해주세요",
		input_mother_tel3 : "부모님(모)전화번호를 입력해주세요",
    	input_member_address : "주소를 입력해주세요.",
    	input_member_email : "이메일주소를 입력해주세요.",
   		input_member_startSearchDate : "성범죄경력조회 확인일자를 선택해주세요.",
    	input_member_startSearchDate2: "교육청 강사등록일자를 선택해주세요.",
		input_myclass_type : "반을 선택해 주세요.",
    	input_assignment_type : "사용여부를 선택해 주세요.",
    	input_schoolType : "학년구분을 선택해 주세요.",
    	input_school : "학년을 선택해 주세요.",
    	input_lecture_price : "수강료를 입력해주세요.",
    	input_class_limit : "정원을 입력해주세요.",

		excess_lecture_reg_student : "등록 가능한 인원수가 초과되었습니다.",


	    input_student_grade:"학생의 학년을 선택해주세요.",
		input_student_name : "학생 이름을 입력하세요.",
    	input_teacher_name : "선생님1 이름을 입력하세요.",
    	input_school_name : "학교이름을 입력하세요.",
    	input_route_number : "노선번호를 입력하세요.",
		input_start_route_name : "시점을 입력하세요.",
		input_attend_time : "등원시간을 입력하세요.",
		input_dismiss_time : "하원시간을 입력하세요.",
		input_apply_start_date : "적용시간 시작일을 입력하세요.",
    	input_apply_end_date : "적용시간 종료일을 입력하세요.",
    	input_lecture_class : "강의를 선택해 주세요.",
		input_lecture_start_time : "강의시작시간을 입력하세요.",
    	input_lecture_end_time : "강의종료시간을 입력하세요.",
    	input_lecture_subject : "과목을 선택해 주세요.",

		payment_error : "결제결과 에러가 발생되었습니다.",
		select_installMent : "할부개월을 선택해주세요.",
		select_cash_receipt_type : "현금영수증을 선택해주세요.",
		select_consult_type : "상담유형을 선택해주세요.",
		select_day : "요일을 선택해주세요.",
		select_school_type : "학교구분을 선택하세요",
		select_region : "지역을 선택하세요",

		file_name_not_allow_korean : "파일명이 한글입니다. 영문으로 바꿔주세요.",
		file_extension_not_allow : "파일확장자는 'JPG, GIF'만 가능합니다.",
		file_size_not_allow_300kb : "첨부된 파일크기가 큽니다. 300KB 이미지만 첨부 가능합니다.",
    	file_size_not_allow_500kb : "첨부된 파일크기가 큽니다. 500KB 까지만 첨부 가능합니다.",
    	certificate_file_extension_not_allow : "파일확장자는 'JPG, GIF, PDF'만 가능합니다.",

		not_attend_log : "출결이력이 없습니다.",
		not_lecture_log : "수강이력이 없습니다",
    	not_consult_log_three : "최근 상담 내역이 없습니다.",
		not_consult_log : "상담 내역이 없습니다.",
    	not_reg_schedule_lecture : "등록된 시간표가 없습니다.",

		search_input_student_name : "학생 이름을 입력 후 검색해주세요.",
    	assignment_class_type : "반 또는 과제를 검색해 주세요.",
   		attend_class_type : "반 또는 학생을 검색해 주세요.",
        search_input_id_name : "이름을 입력해주세요.",
		search_academy : "학원을 검색해주세요.",
    	search_member : "운영자를 검색해 주세요.",
		not_bus_route_info : "노선정보가 없습니다.",
		not_lecture_student_rel : "수강중인 학생이 없습니다.",
    	search_lecture : "강의를 검색해 주세요.",
    	schedule_lecture : "등록된 시간표가 없습니다.",

		success_update : "수정됬습니다",
		send_email : "입력하신 이메일 주소로 아이디를 전송 하였습니다.",
		blank_send_email : "이름 또는 이메일 주소를 확인해 주세요.",
    	input_title : "제목을 입력해 주세요.",
    	input_content : "내용을 입력해 주세요.",

		is_change_confirm : "작성한 내용이 저장되지 않습니다.\n계속하시겠습니까?",

        blank_bus_info : "버스를 검색해 주세요.",

        reg_add_btn_stop_station : "추가 버튼을 클릭하여 정차 위치를 등록해 주세요.",

		auth_error_menu : "메뉴 권한이 없습니다.",
}

